# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-09 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0006_auto_20190509_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='unit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='final_grade',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='mid_grade',
            field=models.FloatField(blank=True),
        ),
    ]
