# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-19 17:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0008_auto_20190509_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(verbose_name='شماره دانش آموزی'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='education_degree',
            field=models.CharField(choices=[('DP', 'دیپلم'), ('AS', 'فوق دیپلم'), ('BA', 'لیسانس'), ('MA', 'فوق لیسانس'), ('PHD', 'دکتری')], max_length=2, verbose_name='مدرک تحصیلی'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='hire_date',
            field=models.DateField(verbose_name='تاریخ استخدام'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='profession',
            field=models.ManyToManyField(to='edu.Course', verbose_name='تخصص'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
