# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-21 07:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0009_auto_20190519_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registers', to='edu.Classroom', verbose_name='کلاس'),
        ),
        migrations.AlterField(
            model_name='register',
            name='is_active',
            field=models.BooleanField(verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='register',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registers', to='edu.Student', verbose_name='دانش آموز'),
        ),
        migrations.AlterField(
            model_name='teacherclasscourse',
            name='class_time',
            field=models.CharField(max_length=100, verbose_name='زمان کلاس'),
        ),
        migrations.AlterField(
            model_name='teacherclasscourse',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_class_courses', to='edu.Classroom', verbose_name='کلاس'),
        ),
        migrations.AlterField(
            model_name='teacherclasscourse',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_class_courses', to='edu.Course', verbose_name='دزس'),
        ),
        migrations.AlterField(
            model_name='teacherclasscourse',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_class_courses', to='edu.Teacher', verbose_name='معلم'),
        ),
    ]
