# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-22 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0010_auto_20190521_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='branch',
            field=models.CharField(choices=[('a', 'الف'), ('b', 'ب'), ('c', 'ج')], default='a', max_length=2, null=True, verbose_name='گروه'),
        ),
        migrations.AlterField(
            model_name='levelfield',
            name='field',
            field=models.CharField(blank=True, choices=[('math', 'ریاضی'), ('natural', 'تجربی'), ('humanity', 'انسانی')], max_length=10, verbose_name='رشته'),
        ),
        migrations.AlterField(
            model_name='levelfield',
            name='level',
            field=models.CharField(choices=[('first', 'اول'), ('second', 'دوم'), ('third', 'سوم')], default='first', max_length=10, verbose_name='پایه'),
        ),
    ]
