# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-27 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0011_auto_20190522_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='branch',
            field=models.CharField(blank=True, choices=[('a', 'الف'), ('b', 'ب'), ('c', 'ج')], default='a', max_length=2, null=True, verbose_name='گروه'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='hire_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ استخدام'),
        ),
    ]
