# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-27 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0012_auto_20190527_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(blank=True, choices=[('1', 'زنگ اول'), ('2', 'زنگ دوم'), ('3', 'زنگ سوم'), ('4', 'زنگ چهارم')], default='1', max_length=20, null=True, verbose_name='زنگ')),
                ('day', models.CharField(blank=True, choices=[('Sa', 'شنبه'), ('Su', 'یکشنبه'), ('Mo', 'دوشنبه'), ('Tu', 'سه شنبه'), ('We', 'چهارشنبه')], default='Sa', max_length=20, null=True, verbose_name='روز')),
            ],
        ),
        migrations.RemoveField(
            model_name='teacherclasscourse',
            name='class_time',
        ),
        migrations.AddField(
            model_name='teacherclasscourse',
            name='class_time',
            field=models.ManyToManyField(to='edu.ClassTime', verbose_name='زمان کلاس'),
        ),
    ]
