# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-28 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0013_auto_20190527_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherclasscourse',
            name='class_time',
            field=models.ManyToManyField(related_name='teacher_class_course', to='edu.ClassTime', verbose_name='زمان کلاس'),
        ),
    ]
