# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-01 09:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0014_auto_20190528_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='assignments')),
                ('sent_time', models.DateTimeField()),
                ('deadline_time', models.DateTimeField()),
                ('grade', models.IntegerField(validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(0)])),
                ('teacher_class_course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='edu.TeacherClassCourse')),
            ],
        ),
    ]
