# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-01 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0016_assignment_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='deadline_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='sent_time',
            field=models.DateField(),
        ),
    ]
