# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-04 11:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0018_auto_20190601_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourse',
            name='final_grade',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='mid_grade',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(0)]),
        ),
    ]
