# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-12 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0019_auto_20190604_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
            preserve_default=False,
        ),
    ]
