# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-12 09:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0020_classroom_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPresence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('presence', models.BooleanField(verbose_name='حضور')),
                ('activity', models.CharField(blank=True, choices=[('pos', '+'), ('neg', '-')], max_length=2, null=True, verbose_name='فعالیت')),
                ('student_course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='edu.StudentCourse')),
            ],
        ),
    ]
