# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-12 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0021_studentpresence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpresence',
            name='activity',
            field=models.CharField(blank=True, choices=[('pos', '+'), ('neg', '-')], max_length=20, null=True, verbose_name='فعالیت'),
        ),
    ]
