# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-06 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0022_auto_20190612_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherPresence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('presence', models.BooleanField(verbose_name='حضور')),
                ('teacher_class_course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='edu.TeacherClassCourse')),
            ],
        ),
    ]
