# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-08 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0019_auto_20190604_1530'),
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='teacher',
        ),
        migrations.AddField(
            model_name='choice',
            name='teacher_class_course',
            field=models.ForeignKey(default=-1.0, on_delete=django.db.models.deletion.CASCADE, to='edu.TeacherClassCourse'),
            preserve_default=False,
        ),
    ]
